-- Real Estate CRM Database Schema
-- MySQL / PostgreSQL compatible

CREATE DATABASE IF NOT EXISTS realestate_crm;
USE realestate_crm;

-- ============================================
-- USERS & AUTH
-- ============================================
CREATE TABLE roles (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE, -- admin, manager, agent
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (name) VALUES ('admin'), ('manager'), ('agent');

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(50),
  password_hash VARCHAR(255) NOT NULL,
  role_id INT NOT NULL DEFAULT 3,
  is_active BOOLEAN DEFAULT TRUE,
  avatar_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- Default admin: admin@crm.com / password123
-- Password hash will be generated by the app seed script

-- ============================================
-- LEAD SOURCES
-- ============================================
CREATE TABLE lead_sources (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO lead_sources (name) VALUES
('Facebook Ads'), ('Referral'), ('WhatsApp'), ('Walk-in'),
('Instagram'), ('Website'), ('Phone Call'), ('Email'), ('Other');

-- ============================================
-- LEADS
-- ============================================
CREATE TABLE leads (
  id INT PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255),
  source_id INT,
  stage ENUM('new_lead','contacted','interested','inspection_scheduled','negotiation','closed_won','closed_lost') DEFAULT 'new_lead',
  assigned_to INT,
  notes TEXT,
  budget_range DECIMAL(15,2),
  property_type VARCHAR(100),
  next_follow_up DATE,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (source_id) REFERENCES lead_sources(id),
  FOREIGN KEY (assigned_to) REFERENCES users(id),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE lead_notes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  lead_id INT NOT NULL,
  user_id INT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================
-- PROPERTIES
-- ============================================
CREATE TABLE properties (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(15,2) NOT NULL,
  location VARCHAR(255) NOT NULL,
  state VARCHAR(100),
  city VARCHAR(100),
  property_type VARCHAR(100), -- land, duplex, apartment, etc.
  bedrooms INT,
  bathrooms INT,
  land_size VARCHAR(100),
  status ENUM('available','reserved','sold') DEFAULT 'available',
  assigned_to INT,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (assigned_to) REFERENCES users(id),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE property_images (
  id INT PRIMARY KEY AUTO_INCREMENT,
  property_id INT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  is_primary BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE
);

-- ============================================
-- DEALS (Sales Pipeline)
-- ============================================
CREATE TABLE deals (
  id INT PRIMARY KEY AUTO_INCREMENT,
  lead_id INT NOT NULL,
  property_id INT,
  agent_id INT NOT NULL,
  deal_value DECIMAL(15,2) NOT NULL,
  stage ENUM('inspection','offer_made','payment_ongoing','closed') DEFAULT 'inspection',
  notes TEXT,
  expected_close_date DATE,
  closed_date DATE,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (lead_id) REFERENCES leads(id),
  FOREIGN KEY (property_id) REFERENCES properties(id),
  FOREIGN KEY (agent_id) REFERENCES users(id),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

-- ============================================
-- PAYMENTS
-- ============================================
CREATE TABLE payments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  deal_id INT NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  payment_date DATE NOT NULL,
  payment_method VARCHAR(100), -- cash, transfer, cheque, POS
  receipt_number VARCHAR(100),
  installment_number INT DEFAULT 1,
  total_installments INT DEFAULT 1,
  notes TEXT,
  recorded_by INT,
  status ENUM('pending','partial','completed') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (deal_id) REFERENCES deals(id),
  FOREIGN KEY (recorded_by) REFERENCES users(id)
);

-- ============================================
-- DOCUMENTS
-- ============================================
CREATE TABLE documents (
  id INT PRIMARY KEY AUTO_INCREMENT,
  property_id INT NOT NULL,
  document_type ENUM('certificate_of_occupancy','survey_plan','deed_of_assignment','other') NOT NULL,
  title VARCHAR(255) NOT NULL,
  file_url VARCHAR(500) NOT NULL,
  status ENUM('pending','verified','flagged') DEFAULT 'pending',
  notes TEXT,
  uploaded_by INT,
  verified_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (property_id) REFERENCES properties(id),
  FOREIGN KEY (uploaded_by) REFERENCES users(id),
  FOREIGN KEY (verified_by) REFERENCES users(id)
);

-- ============================================
-- AUDIT LOGS
-- ============================================
CREATE TABLE audit_logs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  action VARCHAR(255) NOT NULL,
  entity_type VARCHAR(100),
  entity_id INT,
  details JSON,
  ip_address VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX idx_leads_stage ON leads(stage);
CREATE INDEX idx_leads_assigned ON leads(assigned_to);
CREATE INDEX idx_properties_status ON properties(status);
CREATE INDEX idx_deals_stage ON deals(stage);
CREATE INDEX idx_payments_status ON payments(status);
CREATE INDEX idx_payments_deal ON payments(deal_id);
CREATE INDEX idx_documents_status ON documents(status);
